stages:
  - build
  - docker

maven-build:
  image: maven:3-openjdk-17
  stage: build
  script: "mvn clean package -B"
  artifacts:
    paths:
      - appeal-service/target/*.jar
      - doctor-service/target/*.jar
      - nurse-service/target/*.jar

build:
  stage: docker
  image:
    name: gcr.io/kaniko-project/executor:v1.9.0-debug
    entrypoint: [""]
  only:
    - main
  script:
    - mkdir -p /kaniko/.docker
    - echo "{\"auths\":{\"${YC_CI_REGISTRY}\":{\"auth\":\"$(printf "%s:%s" "${YC_CI_REGISTRY_USER}" "${YC_CI_REGISTRY_PASSWORD}" | base64 | tr -d '\n')\"}}}" > /kaniko/.docker/config.json
    - /kaniko/executor
      --context "${CI_PROJECT_DIR}/appeal-service"
      --dockerfile "${CI_PROJECT_DIR}/appeal-service/Dockerfile"
      --destination "${YC_CI_REGISTRY}/${YC_CI_REGISTRY_ID}/andrey4281/appeal-service:${CI_COMMIT_SHA}"
    - /kaniko/executor
      --context "${CI_PROJECT_DIR}/doctor-service"
      --dockerfile "${CI_PROJECT_DIR}/doctor-service/Dockerfile"
      --destination "${YC_CI_REGISTRY}/${YC_CI_REGISTRY_ID}/andrey4281/doctor-service:${CI_COMMIT_SHA}"
    - /kaniko/executor
      --context "${CI_PROJECT_DIR}/nurse-service"
      --dockerfile "${CI_PROJECT_DIR}/nurse-service/Dockerfile"
      --destination "${YC_CI_REGISTRY}/${YC_CI_REGISTRY_ID}/andrey4281/nurse-service:${CI_COMMIT_SHA}"