image: gitlab/dind
services:
  - docker:dind

variables:
  DOCKER_DRIVER: overlay
  USER_GITLAB: andrey4281
  APP_NAME: ambulance-service
  REPO: ambulance-service

stages:
  - build
  - docker

maven-build:
  image: maven:3-openjdk-17
  stage: build
  script: "mvn clean package -B"
  artifacts:
    paths:
      - appeal-service/target/*.jar
      - doctor-service/target/*.jar
      - nurse-service/target/*.jar

docker-build:
  stage: docker
  script:
    - cd ./appeal-service
    - pwd
    - ls -l
    - cd ../
    - cd ./doctor-service
    - pwd
    - ls -l
    - cd ../
    - cd ./nurse-service
    - pwd
    - ls -l