image: docker:19.03.0
services:
  - docker:19.03.0-dind

variables:
  DOCKER_DRIVER: overlay2
  USER_GITLAB: andrey4281
  APP_NAME: ambulance-service
  REPO: ambulance-service
  DOCKER_TLS_CERTDIR: ""

stages:
  - build
  - docker

maven-build:
  image: maven:3-openjdk-17
  stage: build
  before_script:
    - docker info
  script: "mvn clean package -B"
  artifacts:
    paths:
      - appeal-service/target/*.jar
      - doctor-service/target/*.jar
      - nurse-service/target/*.jar

docker-build:
  stage: docker
  before_script:
    - docker info
  script:
    - docker login -u ${YC_CI_REGISTRY_USER} -p ${YC_CI_REGISTRY_PASSWORD} ${YC_CI_REGISTRY}
    - cd ./appeal-service
    - docker build -t ${YC_CI_REGISTRY}/${YC_CI_REGISTRY_ID}/andrey4281/appeal-service:${CI_COMMIT_SHA} .
    - docker push ${YC_CI_REGISTRY}/${YC_CI_REGISTRY_ID}/andrey4281/appeal-service:${CI_COMMIT_SHA}
    - cd ../
    - cd ./doctor-service
    - docker build -t ${YC_CI_REGISTRY}/${YC_CI_REGISTRY_ID}/andrey4281/doctor-service:${CI_COMMIT_SHA} .
    - docker push ${YC_CI_REGISTRY}/${YC_CI_REGISTRY_ID}/andrey4281/doctor-service:${CI_COMMIT_SHA}
    - cd ../
    - cd ./nurse-service
    - docker build -t ${YC_CI_REGISTRY}/${YC_CI_REGISTRY_ID}/andrey4281/nurse-service:${CI_COMMIT_SHA} .
    - docker push ${YC_CI_REGISTRY}/${YC_CI_REGISTRY_ID}/andrey4281/nurse-service:${CI_COMMIT_SHA}